class Actions:
    ASK_QUESTION = "ASK_QUESTION"
    REQUEST_DOCUMENT = "REQUEST_DOCUMENT"
    SHOW_RESULT = "SHOW_RESULT"
    OFFER_OPTION = "OFFER_OPTION"


class Reasons:
    MISSING_FIELD = "MISSING_FIELD"
    MISSING_DOCUMENT = "MISSING_DOCUMENT"
    ELIGIBILITY_FAILED = "ELIGIBILITY_FAILED"
    COMPLETE = "COMPLETE"
    ENHANCEMENT = "ENHANCEMENT"


